bind 0.0.0.0  
port 6399  
databases 16  
maxclients 1000  

appendonly yes  
appendfilename appendonly.aof  
appendfsync everysec  
dbfilename node1.rdb  
dir ./data/node1  

cluster-enable yes  
cluster-as-seed yes  
raft-listen-address 0.0.0.0:16666  
raft-advertise-address 127.0.0.1:16666