# 基础配置  
bind 0.0.0.0  
port 6401  
databases 16  
maxclients 1000  

# 持久化配置  
appendonly yes  
appendfilename appendonly.aof  
appendfsync everysec  
dbfilename node3.rdb  
dir ./data/node3  

# 集群配置  
cluster-enable yes  
cluster-as-seed no  
cluster-seed 127.0.0.1:6399  
raft-listen-address 0.0.0.0:16668  
raft-advertise-address 127.0.0.1:16668